apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:

  - namespace.yaml

  - mysql/ConfigMap.yaml
  - mysql/ConfigMapData.yaml
  - mysql/Secret.yaml
  - mysql/Service.yaml
  - mysql/StorageClass.yaml

  - mysql/statefulset.yaml

  - backend/deployment.yaml
  - backend/service.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - ingress.yaml